golang:
	docker build . -t hello-world-golang -f golang.dockerfile

debian:
	docker build . -t hello-world-debian -f debian.dockerfile

stratch:
	docker build . -t hello-world-stratch -f stratch.dockerfile
